<footer id="appFooter" class="footer">
    <div class="shopaddress col-lg-plus-8 col-lg-8 col-md-8 col-sm-8 col-xs-12">
        Address: <br/>
        <address>
            Bhashantek Branch: Shop No.06, Bhashantek Bazer, Dhaka Cantt, Dhaka-1206, <br/>
            Matikata Branch: Shop No.13, Mannan Tower, Matikata Bazer, Dhaka Cantt, Dhaka-1206, <br/>
            Mobile: 01712264171, 01972264171, 01769110887, E-mail:skfaruk78@yahoo.com.
        </address>
    </div>
    <div class="copyright col-lg-plus-4 col-lg-4 col-md-4 col-sm-4 col-xs-12">

        Social links: <br/>
        <div class="socials-wrap">
            <ul>
                <li class="li-social facebook-social">
                    <a title="Facebook" href="https://www.facebook.com/pg/tasfiqueComputerCenter/" target="_blank">
                        <span class="fab fa-facebook-f icon-social"></span>
                        <span class="name-social">Facebook</span>
                    </a>
                </li>
                <li class="li-social pinterest-social">
                    <a title="Instagram" href="#" target="_blank">
                        <span class="fab fa-instagram icon-social"></span>
                        <span class="name-social">Instagram</span>
                    </a>
                </li>
                <li class="li-social google-social">
                    <a title="Google+" href="#" target="_blank">
                        <span class="fab fa-google-plus-g icon-social"></span>
                        <span class="name-social">Google+</span>
                    </a>
                </li>

                <li class="li-social linkedin-social">
                    <a title="Linkedin" href="#" target="_blank">
                        <span class="fab fa-linkedin-in icon-social"></span>
                        <span class="name-social">Linkedin</span>
                    </a>
                </li>

                <li class="li-social twitter-social">
                    <a title="Twitter" href="#" target="_blank">
                        <span class="fab fa-twitter icon-social"></span>
                        <span class="name-social">Twitter</span>
                    </a>
                </li>

                <li class="li-social pinterest-social">
                    <a title="Pinterest" href="#" target="_blank">
                        <span class="fab fa-pinterest-p icon-social"></span>
                        <span class="name-social">Pinterest</span>
                    </a>
                </li>
            </ul>
        </div>

        <br/>
        Copyright &copy; <?php echo date('Y'); ?> Tasfique Computer Center
    </div>
    <div class="systemFingurePrint col-lg-plus-12 col-lg-12 col-md-12 col-sm-12 col-xs-12 col-xs-plus-12">
        <hr/>
        Developed by
        <a href="https://www.fb.me/mrabir.ahamed" target="_blank" class="link"> <?php echo AppAuthor; ?> </a>
        || Powered by <a href="<?php echo DefaultAppCompanyWebAddress; ?>" target="_blank"
                         class="link"><?php echo DefaultAppName; ?>
        </a>
    </div>
</footer>


<style>
    .socials-wrap .li-social {
        display: inline-block;
        margin: 0 2px;
        vertical-align: top;
    }

    li {
        display: list-item;
        text-align: -webkit-match-parent;
    }

    ul, ol {
        list-style: none;
    }


    .socials-wrap .li-social a .icon-social {
        text-align: center;
        width: 35px;
        height: 35px;
        display: inline-block;
        line-height: 35px;
        color: #fff;
        font-size: 16px;
        transition: 0.1s;
        -moz-transition: 0.1s;
        -webkit-transition: 0.1s;
    }

    .fa {
        display: inline-block;
        font: normal normal normal 14px/1 FontAwesome;
        font-size: inherit;
        text-rendering: auto;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }

    .socials-wrap .li-social a .name-social {
        display: none;
    }

    .socials-wrap .facebook-social a .icon-social {
        background-color: #0f62b7;
    }

    .socials-wrap .pinterest-social a .icon-social {
        background-color: #ef1438;
    }

    .socials-wrap .google-social a .icon-social {
        background-color: #e14938;
    }

    .socials-wrap .linkedin-social a .icon-social {
        background-color: #4080b7;
    }

    .socials-wrap .twitter-social a .icon-social {
        background-color: #41ade2;
    }
</style>