<?php

class Template
{
    public $myName = 'Mishusoft Template Engine';
    public $myVersion = 1;
    public $myAuthor = 'Mr Abir Ahamed';
    public $myCompanyURL = 'https://www.mishusoft.com/';

    public $template_dir = 'template_dir';
    public $config_dir = 'config_dir';
    public $cache_dir = 'cache_dir';
    public $compile_dir = 'compile_dir';
    public $_objType = 4;

    private $tpl_vars = array();
    private $template = '';


    public function __construct()
    {
    }

    public function assign($tpl_var, $nocache = false)
    {
        if (is_array($tpl_var)) {
            foreach ($tpl_var as $_key => $_val) {
                $this->assign($_key, $_val, $nocache);
            }
        }
        return $this;
    }


    public function display($template)
    {
    }


}